version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: search_api
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch
      - redis
    environment:
      PORT: 3000
      ELASTIC_SEARCH_HOST: http://elasticsearch:9200
      REDIS_HOST: redis://redis:6379
      CACHE_TIME: 60
